# Generated by Django 3.2.9 on 2022-01-13 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220112_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='services/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, upload_to='reviews/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Описание'),
        ),
    ]
