# Generated by Django 3.2.9 on 2022-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20220113_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='services',
            field=models.ManyToManyField(to='firstapp.Service', verbose_name='service'),
        ),
    ]
