# Generated by Django 3.2.9 on 2022-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_vehicle_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('data', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описания')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='services',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lugage',
            field=models.CharField(max_length=255, verbose_name='Кузов'),
        ),
    ]
