# Generated by Django 3.2.9 on 2022-01-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20220118_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Экстерьер',
                'verbose_name_plural': 'Экстерьеры',
            },
        ),
        migrations.CreateModel(
            name='VehicleShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='vehicle_shots/', verbose_name='Изображение')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.vehicle')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='character',
            field=models.ManyToManyField(related_name='Характеристики', to='firstapp.Character'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior',
            field=models.ManyToManyField(related_name='Экстерьеры', to='firstapp.Exterior'),
        ),
    ]
