# Generated by Django 3.2.9 on 2022-01-22 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20220120_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='character',
            field=models.ManyToManyField(to='firstapp.Character', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='exterior',
            field=models.ManyToManyField(to='firstapp.Exterior', verbose_name='Экстерьеры'),
        ),
    ]
