# Generated by Django 3.2.9 on 2022-01-22 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20220122_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
