# Generated by Django 3.2.6 on 2021-08-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_wold',
            new_name='fess_in_world',
        ),
    ]
